### PR TITLE
fix: attempt to get the changelog entries to match the prettyrc format.

### PR DESCRIPTION
**Pull request by ategen3rt**
The autogenerated ones are generating with a '*' instead of a '-'.  Hopefully, this changes the text that's inserted so that it matches. Untested.

### CODE REVIEW

**Comment by csell5** [comment]
well ironically, I tried to ignore that file but I did it with eslint. rather than change that autogenerated stuff let's add a .prettierignore and just ignore it.

**Review by csell5 — CHANGES_REQUESTED** [review]
See my earlier comment.

**Comment by ategen3rt** [comment]
That's a good suggestion.  Implementing

**Review by csell5 — APPROVED** [review]

**Pull request merged**
