### PR TITLE
Issue 417 

### PR DESCRIPTION
**Pull request by asharonbaltazar**
Addresses issue #417:

**Problem addressed:**

YouTube links come in two flavors and having just one available meant that sometimes the link was simply wrong.

**Problem fixed:** 

Added a dropdown with consistent styling (thanks to the tailwindcss/forms package), and the selected link is now bundled with the input value.

### CODE REVIEW

**Comment by csell5** [comment]
closes #417

**Review by csell5 — APPROVED** [review]

**Review by csell5 — CHANGES_REQUESTED** [review]
@asharonbaltazar I think we're missing setting the correct option based on a user who already has url set.

**Comment by asharonbaltazar** [comment]
Where should I start looking?

**Comment by csell5** [comment]
If a user already had a url for YouTube. You're going to need to set `selected` for the right option. I'd just do something like selected="{callFunction}" that can figure out if that option is the right one to be selected by default. You might also be able to just bind:value on it and set that, I'd just have to try.

But as it stands right now, I'm pretty sure we would break people's url.

**Comment by asharonbaltazar** [comment]
Should I make this an abstraction? Like should the handling remain exclusive to YouTube links?

**Comment by csell5** [comment]
@asharonbaltazar sorry for being a bit MIA, loads going on trying to get this big feature wrapped up and out. I need to put this on pause a bit otherwise we're going to start having some major conflicts.  I'm hoping we ship later this week, and then we can get things refactored and work through some new planning. Sorry bear with me for a few days.

**Comment by asharonbaltazar** [comment]
Is this feature still on the roster?

**Comment by asharonbaltazar** [comment]
TODO:
Compared to the others, the YouTube link is a bit squished
image

**Comment by csell5** [comment]
yea it's still a thing, I just needed to put it on ice while we got this massive amount of changes through. This for sure needs to get rebased and relooked at as most of that was all touched in some capacity.

**Comment by asharonbaltazar** [comment]
Is there anything I can work on? I have a job now, so perhaps something not complicated if it's prioritized

**Comment by csell5** [comment]
@asharonbaltazar I know it's been a while but now that this was reworked it could come back into focus.

**Comment by asharonbaltazar** [comment]
image

I'm getting an error here. Am I missing something? I ran `npm i`.

**Comment by asharonbaltazar** [comment]
@csell5 Hey, check out these new changes. Updating the slug value and link ending value works. Haven't tried on new accounts, but I think I handled it. Also, please make sure I'm not overdoing things with the various state objects I use to keep track of the values. Overcomplicating things is apparently one of my flaws 😎

**Review by csell5 — CHANGES_REQUESTED** [review]
Once you get this rebased with all the changes off master I'll take a look.

**Comment by asharonbaltazar** [comment]
@csell5 Whenever you can (I know you're super busy), please take a look...

**Comment by asharonbaltazar** [comment]
@csell5 Hey man, I know it's been a while, but maybe we can get this merged someday 😁?

**Review by csell5 — APPROVED** [review]

**Pull request merged**
