### PR TITLE
Sort favorites ascending

### LINKED ISSUE #837: Favorites Sorting
When viewing your favorites the dates listed are sorted in DESC order. The events are then displayed in ASC order for each day.

**To Reproduce**
1. Go to https://that.us/my/favorites - see sorting 

**Expected behavior**
Should the date sorting be in ASC order? Feels counterintuitive as is, but I could be alone on this.

### PR DESCRIPTION
**Pull request by DanWillman**
fixes #837

### CODE REVIEW

**Comment by brettski** [comment]
The reason `my favorites` is currently set to descending order is that the list of favorites spans all events and can get quite long/paged. Having them descending allows the newest ones to be in the list first. The favorites list may need event or day filtering to be more useful in an ascending order.

**Comment by DanWillman** [comment]
Cool, thanks for clarifying. This was the easy fix for the issue (that my coworker and I also noticed), if I get a chance I'll look into adding filtering/etc to make it a bit more useful in an ascending order, as well as letting the user pick. As a conference goer it'd be nice to have the page be a bit more useful on-site, but I completely understand the reasons this solution doesn't work 😄

**Comment by BobDankert** [comment]
@brettski wouldn't it make more sense to list the next upcoming favorited events first (given that the list doesn't appear to show favorited items that have already occurred)? Even with a really long list of favorites, I don't understand why someone would want to see the favorite events that are furthest from the present time first, rather than the other way around (which Dan tried to fix)?

**Comment by brettski** [comment]
@BobDankert Yes I agree the list would make much more sense in ascending order. You make a very good point that not all the favorites are pulled back now. When we implemented the iCal feature for favorites a `historyDays` parameter was added. I forgot about this and see no reason why we can't move forward with changing the favorites to being Ascending order.

**Comment by brettski** [comment]
@DanWillman This PR needs to be brought current and please bump package.json version to `3.11.16`.

**Comment by DanWillman** [comment]
Good catch @BobDankert, I didn't have any previous favorites in my list to see it wasn't displaying them. 

@brettski will do

**Comment by DanWillman** [comment]
Rebased and increased the version number ✅

**Review by brettski — APPROVED** [review]

**Comment by brettski** [comment]
@all-contributors please add @DanWillman for code
@all-contributors please add @BobDankert for ideas

**Pull request merged**
