### PR TITLE
Fixing issue #534

### PR DESCRIPTION
**Pull request by asharonbaltazar**
I copied styles and applied them to the Partner list items to maintain consistency. The items now animate on hover.

Sidenote: I had to add `--no-verify` to my `git` command to bypass testing. What should I do there?

Edit: concerning issue #534

### CODE REVIEW

**Comment by csell5** [comment]
@asharonbaltazar what wasn't working about the verification?

**Review by csell5 — APPROVED** [review]

**Comment by csell5** [comment]
Closes issue #534

**Comment by asharonbaltazar** [comment]
I can't even screenshot it because the console in VS can't scroll that far up... Basically a bunch of errors from some testing/linting?

**Comment by csell5** [comment]
Interesting.. Well that should have failed the build here if it was an issue. let's bring this to a discussion so we can get to the root. https://github.com/ThatConference/that.us/discussions/558

**Comment by asharonbaltazar** [comment]
This should probably have a separate thread. I'll try and get a screenshot with my next PR. I'm closing this thread then.

**Comment by csell5** [comment]
I created a discussion thread about it here -https://github.com/ThatConference/that.us/discussions/558

**Pull request merged**
