### PR TITLE
size jitsi frame to window; add expand/shrink

### LINKED ISSUE #186: Portal Window is too tall
**Describe the bug**
When I launch a meeting the portal window is bigger than the browser window and I miss the bottom buttons

**To Reproduce**
1.  Launch a meeting

### PR DESCRIPTION
**Pull request by saragibby**
closes #186

### CODE REVIEW

**Comment by csell5** [comment]
the button you added to take the frame full width.

image

but it's keeping the left position and taking it off screen.

image

I might also add that button to the left rather than the right since there the right has all of the images of folks in a filmstrip view.

**Comment by saragibby** [comment]
@csell5 covid cut, haha, love it! Not cool that it didn't change the left position. I'll take a look see. And yup, will move to the right as well. 

I'm using the font-awesome icons, what do you think of 'em? I originally was thinking the usual: 
image 
image
But those imply full screen and are already used in the jitsi menu.

**Comment by csell5** [comment]
FA icons are perfect as I already had that all wired in and were using it all over..

and not right side.. move to the left side. away from the filmstrip.

**Comment by saragibby** [comment]
Yeah, went with icons already wired in, selection wasn't huge for this case so just pick the best out of the bunch.

said right, meant left... `!sideOfCurrent` :)

**Comment by csell5** [comment]
for reference this is the list of icons just in case you hadn't seen them. https://fontawesome.com/v4.7.0/icons/ there are some `expand` ones that seem to fit a bit better.

**Comment by saragibby** [comment]
Thanks! That's the list I was looking at. I liked the `arrows-alt` but couldn't find a partner shrink icon. I had `expand` / `collapse` but they were so close. Lemme give them a go with this when I get the Safari issue fixed up to see what we think.

**Pull request merged**
