### PR TITLE
Enables Member Following

### LINKED ISSUE #464: Implement Member Following Feature
Following a member is currently stubbed out but can be implemented now.

### PR DESCRIPTION
**Pull request by csell5**
*Member now
** uses state machine as backing
*** creates actors for activities and followers
* You can now follow a member
* Meta Tags are set based on state machine. 

closes #464

### CODE REVIEW

**Comment by brettski** [comment]
@csell5 clicking on 'my followers' doesn't go to that member's page. The url shows in the address bar, but the site doesn't navigate.

image

**Comment by brettski** [comment]
I can follow myself, my life's complete

**Review by brettski — CHANGES_REQUESTED** [review]
One finding on link from "my followers"

**Comment by brettski** [comment]
Still now working. Now when I click on a follower (who isn't the same person I am looking at) I am brought to the top of the page, but on the same person. The URL does read the person I clicked. 

image

**Comment by csell5** [comment]
Let's try that.. I amended the last commit.

**Review by brettski — APPROVED** [review]

**Pull request merged**
