### PR TITLE
Speaker List for an event (WIP?)

### PR DESCRIPTION
**Pull request by ategen3rt**
Added a list of speakers to the Hybrid and Online events.  Defaults to 20.  Could use a review.  Maybe a new page that lists all speakers for an event too??

### CODE REVIEW

**Comment by csell5** [comment]
FWIW we just added a new query to get the speakers off the event without having to go through sessions.

**Comment by ategen3rt** [comment]
If I add try to just add speakers (even without any fields) the query doesn't return
```export const QUERY_EVENT_BY_SLUG = `
	${eventFieldsFragment}
	query QUERY_EVENT_BY_SLUG ($slug: String) {
		events {
			event (findBy: {slug: $slug}) {
				get {
					...eventFields
					milestones {
						title
						description
						dueDate
					}					
					speakers: {
			
					}
				}
			}
		}
	}
`;```

**Comment by csell5** [comment]
Is eventFields the name of the fragment?



[Sent from Front]
On December 3, 2021, 1:14 PM CST ***@***.******@***.***> wrote:


If I add try to just add speakers (even without any fields) the query doesn't return
```export const QUERY_EVENT_BY_SLUG = `
${eventFieldsFragment}
query QUERY_EVENT_BY_SLUG ($slug: String) {
events {
event (findBy: {slug: $slug}) {
get {
...eventFields
milestones {
title
description
dueDate
}
speakers: {

                                }
                        }
                }
        }
}


`;```

**Comment by ategen3rt** [comment]
Updated to use the new speakers field under the event

**Review by csell5 — APPROVED** [review]

**Pull request merged**
