### PR TITLE
Link to profile on avatar click

### PR DESCRIPTION
**Pull request by GeekOnCoffee**

### CODE REVIEW

**Comment by brettski** [comment]
@GeekOnCoffee  Are you able to add title text of their first name so it shows on hover?

**Comment by GeekOnCoffee** [comment]
@brettski scope creep ;)

**Comment by brettski** [comment]
Yeah, that's cool

**Comment by GeekOnCoffee** [comment]
@brettski I got it added, just using the browser default behavior.

**Comment by brettski** [comment]
> @brettski I got it added, just using the browser default behavior.

That's what I was referring to.

**Pull request merged**
