### PR TITLE
Issue 514

### PR DESCRIPTION
**Pull request by asharonbaltazar**
Communities now appear as a separate list in the filter slide-over. They've been queried along with the rest of the Activities data and formatted into a separate array, which is passed as a prop to `FilterSlideOver`. However, to avoid reinventing the wheel, they've been simply prefixed with an `@` symbol and will get passed as a tag if it's selected. This, IMO, removes the necessity to filter the list in respective to two different arrays, since the tag data (which is identical to the community data) already exists.

### CODE REVIEW

**Comment by asharonbaltazar** [comment]
I really don't know what's going on with the other commits. I just want the commit on this particular branch to show up...

**Comment by csell5** [comment]
@asharonbaltazar FYI, I've been rebasing your branches to keep them in line.

**Comment by csell5** [comment]
So something is still going on here. I know we were going back and forth on the `madison-geek-lunch` so maybe I missed it. It does appear in the list, which is correct as it's part of the query.

```
          {
            "id": "ZdCdwcvGvirBfLnj229X",
            "communities": [
              "that",
              "madison-geek-lunch"
            ]
          },
```

But when you select it, it's not showing up in the filtered list.

http://that.us/activities/ZdCdwcvGvirBfLnj229X While that tag is wrong, it was correct associated because it was correctly tagged in the description of the activity.

**Review by csell5 — CHANGES_REQUESTED** [review]
The activity tags, doesn't have to include the community.

**Comment by asharonbaltazar** [comment]
I'm not sure what you're saying, sorry.

**Comment by csell5** [comment]
I think I found the issue. You need to update the fuse options to also search on `communities`.

```
    keys: [
      'title',
      'shortDescription',
      'tags',
      'speakers.firstName',
      'speakers.lastName',
    ],
```

I created a new activity - https://thatus-hig0e9duu.vercel.app/activities/vnAet3QDbvSo0xUGc50Y. you should be able to filter on @Javascript and see it appear but it doesn't and I think that's because fuse isn't looking there for the search.

**Comment by csell5** [comment]
That's in `components/activities/List.svelte`

**Comment by asharonbaltazar** [comment]
Okay, I'll do that. Just to understand this further, what does `fuse` do?

**Comment by csell5** [comment]
Fuse is the lib that we use to do the actual searching across all of the items - https://fusejs.io/

**Comment by asharonbaltazar** [comment]
Okay, looks good! Should we rename the `selectedTags` variable? I'm asking because it's not holding just tags anymore

**Comment by asharonbaltazar** [comment]
Also I think the UI needs a little refactoring since it's unclear whether one can search for communities... 

What are your thoughts?

**Comment by csell5** [comment]
yes I agree on both accounts.

**Comment by asharonbaltazar** [comment]
Before I start rearranging the UI, please have a look at the commits, thank you.

**Comment by csell5** [comment]
I dig it. Couple items.

* FWIW on mobile the fly out is going to just take over the screen. I don't think it's a bad thing. in fact it might actually be better than what it's doing now.
* I would change the text on the button to be a bit more generic. Since we now have tags and communities, maybe saying `clear N selected items` vs selected tags, since it clears both.
* As for the button, I think I would either drop the border line, or pull it up and put the button under it. Visually it seems to compete for no good reason.

image

**Comment by asharonbaltazar** [comment]
Small problem: I see this `<SlideOver/>` is being used in `ActivitySlideOver`. Are my changes going to break functionality?

**Comment by csell5** [comment]
@asharonbaltazar Sorry for being MIA, trying to get a few features out the door.

I might have misspoken earlier. 

Your button below. There is already a svelte slot for it in the base layout so it should aligns right if you assign your layout to it. All you would need to do is add the following attribute to what you'd like to see in that bottom section. 

```
  slot="panelActions"
```

As for your question on the changes, it shouldn't cause it should be based on slots but I will take a closer look at it here now.

**Comment by csell5** [comment]
The Activity panel looks fine. It also uses the slot I was just talking about

image

**Comment by asharonbaltazar** [comment]
I think those buttons should be consistent somewhat.

**Comment by asharonbaltazar** [comment]
I'm opening another to PR due to an F up

**Pull request closed without merging**
