### PR TITLE
Add activity list tag filter

### LINKED ISSUE #41: Filter Sessions by Tags
On the session list page add the ability to filter the list by a given tag.

### PR DESCRIPTION
**Pull request by jacobmischka**
Styling might need a little work still, suggestions welcome.

image

The two main existing styling issues I'm unsure the best way to solve are:

1.I'm currently just hiding it entirely on mobile because I'm unsure where to put it. I think this is probably fine, though suggestions for better placement on mobile is welcome.
2. When scrolling to the bottom the sticky causes it to look pretty wonky. Granted, this happens to the search bar as well, though since that's much higher up it's a lot less noticeable.

image

Fixes #41

### CODE REVIEW

**Comment by csell5** [comment]
@all-contributors please add @jacobmischka for code

**Comment by csell5** [comment]
@jacobmischka FYI this branch got updated with a readme update.

**Comment by csell5** [comment]
@jacobmischka first.. thank ya for jumping in!

**Comment by csell5** [comment]
@jacobmischka first.. thank ya for jumping in!

some backstory.. You can start to see around the site where you can now start to follow things. We're slowly laying the groundwork to where you can customize how you want to be notified, filter, etc. Plenty of work to do, but I wanted to lay that out there before answering your questions.

Easy first.. Mobile. Yea, I'd just cut it. The current search box will also search tags. It needs to be finger friendly and as you've already noticed the current search box get's a bit janky and that needs to get resolved.

The current layout is going to propose another problem. Check out https://thatus-neef6jyov.vercel.app/events/thatOnline

Few thoughts. 
* I like how it sticks. I could see people digging on that especially during an event. Think more dashboard like were they're just on that page but all they care about is Svelte.
* the current placement clearly doesn't work.. but we could have a panel maybe slide in from the side like we do with the activity center. here is a super quick mockup as an idea to talk through.

https://whimsical.com/63J133kKRg4wS4aCWZQbzW

Thoughts?

**Comment by csell5** [comment]
It would also be nice if those tag preferences also persisted in maybe local storage (for now).

**Comment by csell5** [comment]
and I just thought of another thing... I'm in the middle of adding paging to things, including this list page. Because of that, those tags will only ever be what is brought into view from the api.

That means these tags will be a subset of maybe a larger set. Now @brettski and I have briefly talked about adding API support but it raises other questions as to, like.. if we brought in all tags, do we then change how we query for those sessions and page that result set.

I don't have a solid answer on that, but I'm open to talk through it in more detail. 

At the end of the day, it's there to support the end user to filter out what they don't want to see.

**Comment by jacobmischka** [comment]
I haven't synced them with localstorage yet, and need to add an indicator to the filter button when there are filters applied but the slideover is hidden, but what are your thoughts on the most recent commit?

**Comment by csell5** [comment]
I dig it.. It's much less "in the way" if ya will. I think we should add a _clear_ button, that will reset all filters back to the start.

I'm in the middle of a big PR which will add paging to the /activities and the other pages and things should just automatically update as they refresh.

I know I said local storage earlier, but I'm thinking that should really be session storage so things reset when you come back. people may forget, and those filters appear as if nothing is upcoming.

**Comment by jacobmischka** [comment]
Oh ha, I missed your suggestion to make the button orange, but thankfully we think alike because that's what I did anyway.

Done adding sessionStorage saving, please let me know if there's anything else! If not, if you wouldn't mind accepting this bad boy before the month ends that would be much appreciated; my last Hacktoberfest PR :smiley:.

**Comment by csell5** [comment]
Of course. I can review it right now, but can you rebase on master while I look at things.

**Comment by csell5** [comment]
There seems to be something going on with the click target and focus now. check out this vid. https://www.dropbox.com/s/28idbxw70zddfwi/455VidBug.gif?dl=0

**Comment by jacobmischka** [comment]
Ah, I think it's because I'm naively just toggling on click instead of closing or opening respectively, I think this should resolve the incorrect toggling.

**Review by csell5 — APPROVED** [review]

**Comment by csell5** [comment]
Yea that fixed it! @jacobmischka thank you so much for jumping in on that. I'm sure it went a bit larger than originally anticipated but 🤝  for getting in there and knocking it out. From the looks of it, you've been in Svelte before.

**Comment by jacobmischka** [comment]
Yeah, it's my favorite frontend right now and I was psyched to see that you use it for the site. Also was psyched to see THAT site pop up on the Hacktoberfest list! Hoping next year we'll be able to get together in the Dells again :water_polo:

**Comment by csell5** [comment]
That's awesome.. Always looking for some Svelte Peeps to chat with. FWIW I do stream building this every day at https://unspecified.live if you ever want to come watch me talk to myself coding. 

Thanks again for jumping in and helping. I know the source is a bit of a dumpster fire in places so thank you for ignoring that. If you ever want to jump in on something just let me know.

**Comment by jacobmischka** [comment]
Sweet, followed. For sure, was fun to contribute!

**Pull request merged**
